// Auto-generated from data/board_*.md — do not edit directly
// Run: pnpm exec tsx scripts/convert-boards.ts

export const PREDEFINED_BOARDS_4X4: string[][][] = [
  [
    ["N", "E", "C", "L"],
    ["L", "I", "Z", "U"],
    ["H", "O", "A", "A"],
    ["O", "B", "R", "N"],
  ],
  [
    ["R", "E", "P", "A"],
    ["T", "N", "A", "S"],
    ["O", "Z", "T", "C"],
    ["S", "E", "P", "A"],
  ],
  [
    ["F", "I", "E", "R"],
    ["N", "D", "A", "D"],
    ["I", "E", "O", "U"],
    ["D", "C", "L", "S"],
  ],
  [
    ["C", "C", "S", "O"],
    ["O", "B", "L", "G"],
    ["O", "P", "E", "A"],
    ["L", "A", "I", "R"],
  ],
  [
    ["O", "R", "A", "A"],
    ["L", "D", "T", "M"],
    ["A", "U", "O", "O"],
    ["D", "G", "Z", "N"],
  ],
  [
    ["S", "R", "O", "A"],
    ["O", "A", "S", "S"],
    ["P", "L", "A", "O"],
    ["Z", "E", "A", "C"],
  ],
  [
    ["G", "G", "A", "S"],
    ["J", "N", "O", "Z"],
    ["C", "O", "Y", "A"],
    ["R", "A", "T", "P"],
  ],
  [
    ["C", "R", "N", "A"],
    ["L", "A", "P", "T"],
    ["O", "E", "A", "L"],
    ["V", "S", "U", "Q"],
  ],
  [
    ["I", "A", "F", "A"],
    ["L", "C", "L", "P"],
    ["T", "L", "O", "O"],
    ["E", "A", "J", "S"],
  ],
  [
    ["D", "U", "L", "C"],
    ["C", "I", "N", "E"],
    ["A", "P", "S", "L"],
    ["L", "O", "B", "O"],
  ],
  [
    ["C", "O", "S", "A"],
    ["F", "I", "V", "O"],
    ["M", "R", "N", "D"],
    ["N", "A", "E", "I"],
  ],
  [
    ["A", "M", "A", "O"],
    ["C", "N", "P", "E"],
    ["A", "L", "E", "I"],
    ["V", "O", "D", "R"],
  ],
  [
    ["A", "T", "A", "P"],
    ["I", "V", "O", "D"],
    ["E", "N", "I", "O"],
    ["O", "E", "R", "N"],
  ],
  [
    ["O", "N", "C", "V"],
    ["I", "O", "I", "A"],
    ["D", "D", "T", "N"],
    ["R", "U", "O", "O"],
  ],
  [
    ["R", "A", "E", "O"],
    ["B", "T", "D", "V"],
    ["O", "M", "O", "A"],
    ["A", "N", "D", "N"],
  ],
  [
    ["D", "A", "O", "E"],
    ["U", "T", "I", "C"],
    ["L", "E", "A", "P"],
    ["C", "O", "A", "J"],
  ],
  [
    ["L", "L", "I", "R"],
    ["I", "A", "O", "B"],
    ["S", "A", "T", "O"],
    ["P", "I", "E", "O"],
  ],
  [
    ["J", "O", "L", "E"],
    ["O", "B", "R", "V"],
    ["L", "E", "N", "O"],
    ["A", "E", "S", "O"],
  ],
  [
    ["T", "A", "L", "O"],
    ["Y", "E", "P", "S"],
    ["B", "L", "A", "I"],
    ["O", "T", "O", "R"],
  ],
  [
    ["D", "E", "S", "A"],
    ["I", "E", "L", "N"],
    ["A", "P", "T", "A"],
    ["Y", "O", "J", "O"],
  ],
];

export const PREDEFINED_BOARDS_5X5: string[][][] = [
  [
    ["T", "A", "O", "Y", "A"],
    ["O", "E", "L", "P", "O"],
    ["L", "I", "A", "G", "J"],
    ["G", "S", "M", "H", "O"],
    ["A", "N", "A", "R", "O"],
  ],
  [
    ["R", "E", "N", "I", "B"],
    ["O", "I", "C", "E", "V"],
    ["C", "L", "R", "S", "A"],
    ["E", "A", "L", "A", "N"],
    ["T", "I", "A", "B", "C"],
  ],
  [
    ["A", "O", "Z", "T", "S"],
    ["G", "L", "I", "A", "A"],
    ["L", "A", "L", "O", "P"],
    ["R", "A", "B", "R", "E"],
    ["T", "I", "J", "N", "E"],
  ],
  [
    ["N", "I", "S", "L", "A"],
    ["A", "R", "L", "A", "O"],
    ["E", "V", "E", "H", "R"],
    ["O", "C", "N", "L", "P"],
    ["L", "A", "O", "B", "A"],
  ],
  [
    ["A", "O", "L", "A", "O"],
    ["R", "B", "E", "A", "C"],
    ["E", "A", "J", "D", "R"],
    ["L", "N", "S", "Z", "I"],
    ["A", "C", "O", "E", "N"],
  ],
  [
    ["H", "A", "N", "O", "I"],
    ["O", "A", "N", "O", "C"],
    ["I", "R", "Z", "A", "E"],
    ["J", "A", "M", "T", "S"],
    ["Y", "O", "N", "E", "A"],
  ],
  [
    ["T", "O", "A", "T", "E"],
    ["A", "N", "R", "C", "L"],
    ["P", "N", "S", "D", "I"],
    ["D", "A", "A", "C", "I"],
    ["A", "L", "I", "B", "U"],
  ],
  [
    ["G", "A", "E", "L", "M"],
    ["T", "R", "O", "A", "P"],
    ["N", "M", "S", "A", "A"],
    ["E", "R", "A", "P", "G"],
    ["T", "T", "O", "Y", "O"],
  ],
  [
    ["O", "I", "B", "A", "O"],
    ["N", "R", "I", "C", "J"],
    ["A", "L", "E", "A", "L"],
    ["J", "O", "N", "A", "A"],
    ["V", "E", "S", "T", "N"],
  ],
  [
    ["M", "O", "T", "D", "P"],
    ["I", "A", "P", "A", "A"],
    ["D", "L", "L", "E", "T"],
    ["A", "N", "B", "I", "R"],
    ["R", "S", "A", "U", "N"],
  ],
  [
    ["I", "G", "A", "T", "C"],
    ["R", "A", "J", "A", "S"],
    ["S", "O", "L", "E", "C"],
    ["H", "E", "A", "O", "U"],
    ["A", "R", "D", "Q", "R"],
  ],
  [
    ["A", "N", "T", "M", "O"],
    ["E", "S", "E", "R", "O"],
    ["C", "N", "O", "I", "F"],
    ["I", "R", "C", "A", "N"],
    ["P", "A", "S", "T", "U"],
  ],
  [
    ["A", "O", "L", "F", "U"],
    ["R", "S", "E", "N", "C"],
    ["G", "B", "M", "I", "O"],
    ["O", "A", "A", "R", "F"],
    ["T", "L", "I", "L", "A"],
  ],
  [
    ["E", "V", "R", "C", "O"],
    ["O", "B", "I", "A", "N"],
    ["L", "U", "N", "I", "M"],
    ["A", "E", "N", "O", "P"],
    ["R", "A", "T", "A", "A"],
  ],
  [
    ["A", "N", "A", "R", "N"],
    ["V", "E", "I", "O", "O"],
    ["I", "F", "M", "H", "Z"],
    ["N", "R", "O", "A", "A"],
    ["U", "O", "C", "R", "N"],
  ],
  [
    ["T", "L", "D", "L", "F"],
    ["E", "A", "O", "R", "A"],
    ["L", "G", "N", "A", "J"],
    ["L", "A", "V", "N", "R"],
    ["C", "O", "N", "A", "M"],
  ],
  [
    ["Z", "V", "S", "B", "T"],
    ["O", "A", "I", "A", "I"],
    ["R", "N", "R", "L", "C"],
    ["R", "U", "I", "A", "O"],
    ["E", "G", "P", "N", "T"],
  ],
  [
    ["E", "N", "M", "R", "T"],
    ["R", "T", "E", "A", "O"],
    ["M", "A", "A", "B", "S"],
    ["O", "L", "A", "N", "A"],
    ["E", "T", "P", "A", "Z"],
  ],
  [
    ["L", "T", "P", "O", "N"],
    ["O", "A", "Z", "A", "A"],
    ["O", "T", "S", "I", "D"],
    ["O", "L", "E", "E", "T"],
    ["C", "I", "E", "R", "O"],
  ],
  [
    ["N", "A", "T", "O", "S"],
    ["G", "A", "N", "E", "R"],
    ["N", "T", "L", "E", "S"],
    ["O", "I", "E", "A", "G"],
    ["M", "T", "M", "L", "L"],
  ],
];

export const PREDEFINED_BOARDS_6X6: string[][][] = [
  [
    ["Z", "A", "L", "B", "R", "F"],
    ["P", "I", "A", "L", "A", "O"],
    ["A", "T", "E", "T", "N", "C"],
    ["O", "R", "S", "D", "E", "I"],
    ["T", "I", "E", "A", "G", "O"],
    ["A", "L", "F", "L", "R", "G"],
  ],
  [
    ["A", "N", "T", "R", "A", "L"],
    ["I", "M", "O", "J", "D", "Q"],
    ["A", "I", "I", "I", "U", "L"],
    ["N", "C", "M", "N", "O", "G"],
    ["A", "O", "A", "E", "I", "S"],
    ["T", "N", "C", "E", "R", "A"],
  ],
  [
    ["F", "A", "M", "C", "A", "Z"],
    ["A", "S", "O", "J", "E", "M"],
    ["O", "P", "I", "R", "A", "Z"],
    ["R", "T", "B", "R", "O", "N"],
    ["G", "A", "I", "A", "N", "A"],
    ["S", "A", "L", "I", "R", "P"],
  ],
  [
    ["C", "A", "O", "R", "I", "M"],
    ["H", "I", "S", "T", "O", "A"],
    ["T", "C", "T", "N", "M", "T"],
    ["U", "R", "N", "A", "T", "E"],
    ["L", "A", "A", "A", "L", "A"],
    ["S", "B", "R", "P", "L", "G"],
  ],
  [
    ["P", "A", "L", "S", "A", "R"],
    ["O", "C", "M", "A", "B", "J"],
    ["L", "S", "T", "A", "N", "A"],
    ["S", "O", "E", "L", "A", "R"],
    ["I", "T", "S", "M", "L", "A"],
    ["K", "A", "E", "I", "L", "N"],
  ],
  [
    ["B", "A", "A", "N", "O", "M"],
    ["A", "N", "R", "D", "P", "C"],
    ["I", "O", "T", "O", "A", "U"],
    ["C", "I", "J", "U", "L", "T"],
    ["O", "S", "E", "G", "E", "A"],
    ["L", "T", "U", "T", "H", "M"],
  ],
  [
    ["U", "A", "R", "O", "S", "E"],
    ["R", "Q", "G", "A", "C", "D"],
    ["U", "E", "L", "P", "A", "S"],
    ["E", "T", "I", "A", "M", "T"],
    ["S", "A", "B", "E", "R", "I"],
    ["I", "C", "I", "T", "O", "N"],
  ],
  [
    ["E", "L", "C", "T", "N", "O"],
    ["A", "M", "E", "O", "A", "M"],
    ["A", "S", "A", "N", "A", "N"],
    ["A", "T", "N", "R", "A", "J"],
    ["E", "A", "A", "O", "I", "S"],
    ["P", "R", "F", "R", "P", "O"],
  ],
  [
    ["O", "I", "R", "T", "E", "L"],
    ["S", "N", "S", "A", "A", "P"],
    ["I", "E", "C", "E", "U", "M"],
    ["E", "V", "A", "N", "O", "T"],
    ["T", "L", "O", "R", "A", "C"],
    ["E", "Z", "A", "D", "O", "E"],
  ],
  [
    ["A", "N", "A", "N", "A", "O"],
    ["T", "O", "S", "T", "F", "N"],
    ["N", "R", "M", "A", "C", "I"],
    ["E", "O", "E", "R", "M", "T"],
    ["P", "U", "R", "A", "A", "E"],
    ["G", "A", "N", "M", "T", "L"],
  ],
  [
    ["P", "R", "T", "P", "F", "N"],
    ["C", "I", "A", "I", "A", "O"],
    ["T", "U", "N", "E", "A", "R"],
    ["E", "A", "L", "O", "M", "R"],
    ["L", "R", "L", "A", "D", "E"],
    ["A", "T", "E", "H", "G", "U"],
  ],
  [
    ["O", "N", "I", "L", "I", "T"],
    ["C", "A", "A", "C", "N", "O"],
    ["A", "E", "A", "D", "E", "V"],
    ["G", "M", "A", "I", "O", "R"],
    ["I", "H", "R", "N", "A", "E"],
    ["N", "O", "P", "Z", "C", "S"],
  ],
  [
    ["O", "O", "L", "S", "I", "L"],
    ["M", "S", "S", "E", "E", "A"],
    ["A", "M", "A", "R", "D", "S"],
    ["F", "R", "N", "T", "O", "A"],
    ["I", "A", "O", "I", "Y", "N"],
    ["G", "P", "I", "C", "O", "U"],
  ],
  [
    ["F", "I", "N", "F", "G", "I"],
    ["I", "T", "L", "O", "R", "A"],
    ["E", "A", "A", "M", "S", "I"],
    ["N", "R", "J", "A", "F", "O"],
    ["A", "I", "T", "I", "R", "P"],
    ["A", "C", "Z", "N", "D", "I"],
  ],
  [
    ["T", "N", "O", "D", "O", "A"],
    ["N", "A", "M", "Z", "A", "R"],
    ["R", "A", "E", "T", "O", "P"],
    ["A", "L", "U", "C", "M", "A"],
    ["G", "A", "L", "P", "T", "L"],
    ["P", "I", "L", "I", "E", "A"],
  ],
  [
    ["O", "N", "A", "B", "L", "S"],
    ["I", "N", "A", "L", "A", "O"],
    ["A", "C", "I", "M", "N", "T"],
    ["T", "N", "O", "T", "A", "I"],
    ["E", "V", "P", "A", "C", "A"],
    ["U", "I", "Z", "A", "F", "I"],
  ],
  [
    ["I", "A", "C", "E", "R", "A"],
    ["G", "O", "N", "T", "I", "E"],
    ["O", "L", "A", "L", "N", "V"],
    ["A", "N", "B", "A", "O", "M"],
    ["I", "O", "F", "R", "D", "I"],
    ["A", "C", "C", "S", "O", "K"],
  ],
  [
    ["D", "O", "H", "C", "I", "N"],
    ["A", "E", "O", "E", "E", "A"],
    ["G", "L", "A", "N", "S", "B"],
    ["A", "T", "E", "T", "O", "A"],
    ["E", "L", "M", "L", "S", "R"],
    ["L", "I", "A", "E", "O", "I"],
  ],
  [
    ["M", "T", "E", "M", "I", "A"],
    ["A", "C", "A", "C", "A", "T"],
    ["I", "N", "S", "R", "L", "E"],
    ["G", "O", "Q", "S", "T", "C"],
    ["L", "L", "E", "U", "I", "T"],
    ["B", "O", "G", "I", "A", "O"],
  ],
  [
    ["V", "N", "E", "T", "R", "O"],
    ["E", "T", "O", "M", "E", "F"],
    ["N", "A", "P", "D", "I", "S"],
    ["Z", "A", "A", "R", "E", "N"],
    ["L", "T", "R", "C", "U", "M"],
    ["I", "L", "E", "O", "P", "I"],
  ],
];

// Words declared in markdown files (for test verification)
export const DECLARED_WORDS: Record<string, string[][]> = {
  "4": [
    ["CIELO", "CINE", "HORA", "LOBO", "RANA", "LUZ"],
    ["ANTES", "CANTO", "TREPA", "CASA", "PATA", "TAPA", "TREN", "PEZ"],
    ["CIELO", "DULCE", "CINE", "DADO", "IDEA", "NIDO", "FIN", "RED"],
    ["RIEGO", "BOLA", "COPA", "LAGO", "LOBO", "PIEL", "PIE", "SOL"],
    ["DADO", "LAGO", "MONO", "NOTA", "RATA", "LUZ", "MAR", "OLA"],
    ["CASA", "CASO", "PALO", "ROSA", "SALA", "OLA", "OSO", "PEZ"],
    ["ARCO", "JOYA", "PATO", "RATA", "TACO", "TAZA", "ZONA", "GAS"],
    ["VOLCAN", "QUESO", "PATA", "RANA", "TAPA", "VELA", "SAL", "SOL"],
    ["FACIL", "COPA", "PALO", "TELA", "OJO", "OLA", "OSO", "SOL"],
    ["DULCE", "CINE", "LOBO", "PALO", "PISO", "OLA", "OSO", "SOL"],
    ["CINE", "IDEA", "VASO", "VINO", "FIN", "MAR", "OSO", "RIO"],
    ["VOLCAN", "CAMPO", "PIEL", "OLA", "PAN", "PIE", "RED"],
    ["ENERO", "NIDO", "NOTA", "ODIO", "PATA", "PATO", "VINO", "RIO"],
    ["CANTO", "NIDO", "NOTA", "ODIO", "RUTA", "TACO", "VINO"],
    ["ARTE", "BOTA", "DADO", "MANO", "MONO", "NAVE", "NOTA"],
    ["CIELO", "DULCE", "CAJA", "PATA", "PATO", "PIEL", "TACO", "PIE"],
    ["SILLA", "BOLA", "BOTA", "LOBO", "PATA", "PATO", "PIE", "RIO"],
    ["ENERO", "BOLA", "LOBO", "LORO", "VELO", "OJO", "OLA", "OSO"],
    ["BOLA", "PATO", "TELA", "YATE", "OLA", "RIO", "SAL", "SOL"],
    ["ANTES", "IDEA", "JOYA", "PIEL", "SALA", "TELA", "OJO", "SAL"],
  ],
  "5": [
    [
      "HORMIGA",
      "ISLOTE",
      "MALETA",
      "JOYA",
      "LAGO",
      "PALO",
      "RANA",
      "SALA",
      "YOGA",
    ],
    [
      "BICICLETA",
      "BAILARIN",
      "TELARANA",
      "ENERO",
      "CASA",
      "NAVE",
      "RANA",
      "SALA",
      "TACO",
    ],
    ["LAGARTIJA", "ZAPATILLA", "ENERO", "BOLA", "LAGO", "PALO", "SALA", "TAPA"],
    [
      "NEVERA",
      "VOLCAN",
      "SILLA",
      "BOLA",
      "HORA",
      "NAVE",
      "PALO",
      "SALA",
      "VELO",
    ],
    [
      "ESCALERA",
      "JARDIN",
      "ARCO",
      "BOLA",
      "CAJA",
      "IDEA",
      "RANA",
      "SALA",
      "ZONA",
    ],
    [
      "ZANAHORIA",
      "MONTANA",
      "OCEANO",
      "CASA",
      "HORA",
      "JOYA",
      "MANO",
      "MESA",
      "ZONA",
    ],
    [
      "BICICLETA",
      "SANDALIA",
      "LADRON",
      "ARTE",
      "CASA",
      "PATO",
      "RANA",
      "SALA",
      "TAPA",
    ],
    [
      "RELAMPAGO",
      "TORMENTA",
      "ARTE",
      "PALO",
      "PATO",
      "ROSA",
      "TAPA",
      "YATE",
      "YOGA",
    ],
    [
      "BAILARIN",
      "VENTANA",
      "OCEANO",
      "CIELO",
      "ENERO",
      "RELOJ",
      "CAJA",
      "SALA",
    ],
    ["LIBERTAD", "SANDALIA", "MALETA", "NUBE", "PATO", "RANA", "SALA", "TAPA"],
    [
      "ESCALERA",
      "ORQUESTA",
      "GIRASOL",
      "HELADO",
      "RELOJ",
      "CAJA",
      "HORA",
      "SALA",
      "TACO",
    ],
    [
      "PRINCESA",
      "UNIFORME",
      "ANTES",
      "ENERO",
      "ARCO",
      "CASA",
      "MESA",
      "ROSA",
      "TACO",
    ],
    [
      "BAILARIN",
      "UNIFORME",
      "CIELO",
      "BOLA",
      "FLOR",
      "GATO",
      "LAGO",
      "MESA",
      "ROSA",
    ],
    [
      "TELARANA",
      "CAMINO",
      "ARCO",
      "BOLA",
      "MANO",
      "NUBE",
      "PATO",
      "TAPA",
      "VINO",
    ],
    [
      "ZANAHORIA",
      "UNIFORME",
      "CORAZON",
      "ARCO",
      "HORA",
      "NAVE",
      "RANA",
      "VINO",
    ],
    ["GALLETA", "NARANJA", "LADRON", "VOLCAN", "FLOR", "LAGO", "MANO", "RANA"],
    [
      "BAILARIN",
      "GUERRA",
      "CASA",
      "PALO",
      "PATO",
      "SALA",
      "TACO",
      "VINO",
      "ZONA",
    ],
    [
      "TORMENTA",
      "MALETA",
      "SABANA",
      "ZAPATO",
      "ENERO",
      "ARTE",
      "PALO",
      "PATO",
      "ROSA",
    ],
    ["DESIERTO", "ISLOTE", "ZAPATO", "CIELO", "PALO", "PATO", "TAPA", "ZONA"],
    ["GALLETA", "MONTANA", "MALETA", "ANTES", "ENERO", "GATO", "MITO", "SALA"],
  ],
  "6": [
    [
      "GEOGRAFIA",
      "ZAPATILLA",
      "DESIERTO",
      "FRONTERA",
      "ABANICO",
      "IGLESIA",
      "PALABRA",
      "ZAPATO",
    ],
    [
      "MECANICA",
      "GIRASOL",
      "MONTANA",
      "QUIMICA",
      "CAMINO",
      "JARDIN",
      "LADRON",
      "OCEANO",
    ],
    [
      "LAGARTIJA",
      "BAILARIN",
      "MARIPOSA",
      "PANORAMA",
      "CORAZON",
      "FAMOSO",
      "OCEANO",
      "SABANA",
    ],
    [
      "MATEMATICAS",
      "PARTICULAR",
      "HISTORIA",
      "TELARANA",
      "GALLETA",
      "MONTANA",
      "MALETA",
      "SABANA",
    ],
    [
      "TELARANA",
      "NARANJA",
      "PALABRA",
      "SEMILLA",
      "ISLOTE",
      "KIOSCO",
      "MALETA",
      "SABANA",
    ],
    [
      "COMPUTADORA",
      "ABANICO",
      "JUGUETE",
      "NOTICIA",
      "HELADO",
      "ISLOTE",
      "LADRON",
      "MALETA",
    ],
    [
      "RELAMPAGO",
      "BAILARIN",
      "ESCALERA",
      "LIBERTAD",
      "ORQUESTA",
      "NOTICIA",
      "CAMINO",
      "MALETA",
    ],
    [
      "FANTASMA",
      "FRONTERA",
      "MARIPOSA",
      "PANORAMA",
      "MONTANA",
      "NARANJA",
      "MALETA",
      "OCEANO",
    ],
    [
      "COMPUTADORA",
      "TELEVISION",
      "NECESARIO",
      "TELARANA",
      "CORAZON",
      "LADRON",
      "MALETA",
      "OCEANO",
    ],
    [
      "MATEMATICAS",
      "AEROPUERTO",
      "FANTASMA",
      "TELARANA",
      "MONTANA",
      "CAMINO",
      "GUERRA",
      "MALETA",
    ],
    [
      "PARTICULAR",
      "PANORAMA",
      "TELARANA",
      "UNIFORME",
      "GALLETA",
      "GUERRA",
      "HELADO",
      "MALETA",
    ],
    [
      "VENTILADOR",
      "ZANAHORIA",
      "MECANICA",
      "PRINCESA",
      "HORMIGA",
      "NOTICIA",
      "CAMINO",
      "OCEANO",
    ],
    [
      "DESAYUNO",
      "DESIERTO",
      "FANTASMA",
      "PANORAMA",
      "GIRASOL",
      "NOTICIA",
      "FAMOSO",
      "LADRON",
    ],
    [
      "INFORMATICA",
      "FILOSOFIA",
      "FRONTERA",
      "MARIPOSA",
      "GIRASOL",
      "MONTANA",
      "FAMOSO",
      "JARDIN",
    ],
    [
      "COMPUTADORA",
      "ZAPATILLA",
      "TELARANA",
      "CORAZON",
      "GALLETA",
      "MONTANA",
      "MALETA",
      "OCEANO",
    ],
    [
      "ZAPATILLA",
      "ABANICO",
      "MONTANA",
      "NOTICIA",
      "VENTANA",
      "CAMINO",
      "SABANA",
      "ZAPATO",
    ],
    [
      "TECNOLOGIA",
      "VENTILADOR",
      "FRONTERA",
      "ABANICO",
      "MONTANA",
      "VENTANA",
      "KIOSCO",
      "LADRON",
    ],
    [
      "NECESARIO",
      "ABANICO",
      "GALLETA",
      "SEMILLA",
      "HELADO",
      "ISLOTE",
      "MALETA",
      "OCEANO",
    ],
    [
      "ARQUEOLOGIA",
      "MATEMATICAS",
      "ARQUITECTO",
      "TECNOLOGIA",
      "MECANICA",
      "TELARANA",
      "IGLESIA",
      "MALETA",
    ],
    [
      "IMPORTANTE",
      "ZAPATILLA",
      "DESIERTO",
      "RECUERDO",
      "UNIFORME",
      "MONTANA",
      "VENTANA",
      "ZAPATO",
    ],
  ],
};
